title: Gordon Duffley
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gduffley.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Gordon Duffley # add your name
author-img: headshot.png # add your photo
about-author: "Test" # add description
social-twitter: gordonduffley
social-facebook: # add your Facebook handle
social-github: gduffley # add your Github handle
social-linkedin: gordon-duffley
social-email: gordonduffley@gmail.com

# Disqus
#discus-identifier: Gordon Duffley # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

emptyArray: []

 comments:
  receiver: https://haacked-blog.azurewebsites.net/api/PostComment

 authors:
  haacked:
    name: haacked
    email: haacked@gmail.com
    url: https://haacked.com

 defaults:
  -
    scope:
      path: ''
      type: pages
    values:
      layout: page
      author: haacked
  -
    scope:
      path: '_posts'
      type: posts
    values:
      layout: post
      author: haacked
